repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        # Needed to allow the mkdocs.yml config file to be linted by pre-commit
        args: [--unsafe]
      # Exlclude the prompts
      - id: end-of-file-fixer
        exclude: ^(examples|src)/.*\.md$
      - id: trailing-whitespace
        exclude: ^(examples|src)/.*\.md$

  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff lint
        entry: uv run ruff check --fix --exit-non-zero-on-fix
        language: system
        types: [python]
        pass_filenames: false
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types: [python]
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
        pass_filenames: false
